### ISSUE TITLE
Scrape [ALL] Club Data

### ISSUE THREAD

**Issue by econnerty** [SCCapstone/CampusConnect#141]

**Comment by challison404** [comment]
Working on fixing a bug that limits organizations being scraped using this from 70 to all 609.

**Comment by challison404** [comment]
Moved to 1.0 Release Milestone as this is proving to be more difficult than previously thought. Will most likely go with some manual solution

**Comment by challison404** [comment]
Created an updated club scraper which can be run to scrape the data of ALL 628 clubs and put them in a json file which is used in the clubsscreen. The club scraper works dynamically so if there are more clubs added/removed it can be run again to update the json file. The scraper will use default values if something goes wrong, or if the club has not yet set a custom image it will use a default gamecock logo.
