### ISSUE TITLE
Group creation leads to blank page

### ISSUE THREAD

**Issue by econnerty** [SCCapstone/CampusConnect#168]
It's already fixed, I just wanted to point it out for the beta release.

The group is still created, you may have to force close the app though. @josemvidal @JPSharp

**Comment by josemvidal** [comment]
Still leads to blank page. Have to kill app and start it again:


https://user-images.githubusercontent.com/228704/222211353-7083a19d-ff22-4094-91e0-96c433bae81a.mp4

**Comment by econnerty** [comment]
I know that. I haven't updated the binary. It is fixed.

**Comment by josemvidal** [comment]
**Tip:** When you close an issue by writing code, either fixing a bug or creating a new feature, you should add a link to the git-commit(s) that did it.

This can be done automatically if you just write "closes #X" in the comment of the git-commit or the pull request, where X is the issue number you want to close. See [linking pull requests to issues using keywords](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for more information, or [watch this video](https://youtu.be/WMykv2ZMyEQ).

You should also write "#X" on any commit that is for #X. That commit will then get automatically linked to the Issue.

See my [github tips list](https://capstone.cse.sc.edu/lecture/github-issues/#tips) for all the tips.

**Comment by econnerty** [comment]
It's up there. 3 comments up 😀https://github.com/SCCapstone/CampusConnect/commit/37e2a08d3ccd6a7f187c363f173b8f383af56d19

**Comment by josemvidal** [comment]
Yup, I missed it.
