### ISSUE TITLE
@Tim-Kranz-17 has 0 commits in 492

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/CampusConnect#170]
You have [0 code commits in 492](https://github.com/SCCapstone/CampusConnect/commits?author=Tim-Kranz-17).

>  Team members in CSCE 492 who do little or no programming will fail the class.

https://capstone.cse.sc.edu/492syllabus/#personal-contribution

This is a readme Issue. Read it then close it.

**Comment by econnerty** [comment]
I can vouch that @Tim-Kranz-17 has commits but he has 
1. Still not setup his GitHub account correctly
2. Not pushed his website commits to main, so they are not appearing

@josemvidal

**Comment by josemvidal** [comment]
https://capstone.cse.sc.edu/492syllabus/#github-submissions

> All the code that you write for this class must be in git and pushed to your team's GitHub repo. You will turn in everything else in your GitHub wiki. In other words, everything you do will be in your github repo. If it is not there, you will not receive credit for it. The [academic integrity](https://capstone.cse.sc.edu/492syllabus/#academic-integrity) section explains what happens if you use someone else's GitHub account or commit code that you did not write.

**Comment by econnerty** [comment]
I have told him to setup his GitHub account correctly, but as of now, some of the things he contributed to are showing 1 contributor (me) because he committed from an improper account.

**Comment by josemvidal** [comment]
https://capstone.cse.sc.edu/492syllabus/#academic-integrity

> In this class using someone else's github account, doing a git commit using someone else's identity, or committing code written by a team-mate or someone else, are all considered forms of cheating. This offense will be treated exactly the same as taking a test for someone else. If it is done with the consent of the other person then both people are equally at fault. All cases will result in a formal report to the [Office of Academic Integrity](https://www.sa.sc.edu/academicintegrity/), which might lead to expulsion from USC.

**Comment by josemvidal** [comment]
Do I need to report the both of you?

**Comment by econnerty** [comment]
For what? We have not committed code on each other's accounts? No one in this group has done that.

And what are you looking at? I see his commits here.

<img width="937" alt="Screenshot 2023-03-01 at 10 11 01 AM" src="https://user-images.githubusercontent.com/13265359/222180623-caa93484-b051-48f6-ac37-eb3d30cd8455.png">

**Comment by econnerty** [comment]
You're acting like a robot and not listening. No code written by Tim has been committed by me. There have been refactors, but no code has been committed between team members in this group. I was referring to the way GitHub does not display correctly if the account is not verified.

**Comment by josemvidal** [comment]
Got it. Just making sure "some of the things he contributed to are showing 1 contributor (me) because he committed from an improper account" does not mean he committed from your account.

**Comment by econnerty** [comment]
No, it means "GitHub is bugged and Tim also has not configured his account correctly" an nothing more.
