### ISSUE TITLE
Cannot upload photo for post

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/CampusConnect#172]
I can upload photo to change my profile photo, but not for the posts:

https://user-images.githubusercontent.com/228704/222207760-103df122-c65d-4f35-9ade-d1d23b26adaa.mp4

**Comment by econnerty** [comment]
You have no photos on your emulator?

**Comment by econnerty** [comment]
This feature has been tested extensively, so I'm a bit skeptical.

**Comment by econnerty** [comment]
![Screenshot_20230301-115633](https://user-images.githubusercontent.com/13265359/222208661-e90a8658-ff9d-49f0-898f-6f5aefb008f3.png)

**Comment by josemvidal** [comment]
This is the profile change of photo, which works:

https://user-images.githubusercontent.com/228704/222211953-3615a1e3-486a-4a5a-9f36-a39367632868.mp4

**Comment by econnerty** [comment]
Different API, for each case. The posts screen allows gifs and photos, whereas the profile one only allows photos. I can verify the posts one works on physical hardware and on my emulator. Your environment must not be configured properly to run this app, or appropriate permissions were not given.

**Comment by econnerty** [comment]
If you can replicate this on physical hardware, we will reopen it. Until then, there is overwhelming evidence this feature works.

**Comment by josemvidal** [comment]
@JPSharp please check on this Issue.

**Comment by econnerty** [comment]
We also recommend a clean install, whether in emulator or physical device. This means clearing the data from the app and uninstalling it from the phone. There have been tons of additions and moving parts to this app since the last release.

**Comment by JPSharp** [comment]
![Screenshot_2023-03-01-13-40-08-11_6f7d86b266d81fe545a759404445d633.jpg](https://user-images.githubusercontent.com/44646798/222234522-3b35cb99-7e33-4810-bba0-e92703edf34c.jpg)

I was able to post a picture. @josemvidal

**Comment by econnerty** [comment]
So close? If Dr. Vidal is not able to test on a physical device (iPhone or Android) I think this should be closed.

**Comment by econnerty** [comment]
Modern android phones do not store pictures inside of a folder named 'Photos' anymore. I'm not sure how you got all those images on your emulator, but they do not represent the way normal phone would behave, and you could always move them to either the 'Downloads' or 'Pictures' folder to get them to show up. My physical device is over a year old with hundreds of pictures, but none of them have ever been saved to a folder named 'Photos' like your video shows.

**Comment by econnerty** [comment]
Investigation is done. Only certain folders are valid. These folders are already used by default, so there are usaully no issues in real world use. If you want, you can upload photos to the AVD file explorer in these valid directories to get your photos to show up. You will have stop the emulator and do a cold boot after.

![Screenshot 2023-03-02 100259](https://user-images.githubusercontent.com/13265359/222466110-e924be34-c9c8-4aa1-acc9-e92a598b08e8.png)
