### ISSUE TITLE
Post should be button

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/CampusConnect#173]
<img width="353" alt="image" src="https://user-images.githubusercontent.com/228704/222208271-aeb0541c-97e5-4ea4-97a0-6863944a4327.png">

**Comment by econnerty** [comment]
This one is debatable and possibly goes against our design philosophy.

**Comment by econnerty** [comment]
We'd consider making it more apparent that the post button is a button by surrounding it with some different color, but we don't see a point in moving it. This app obviously draws some design inspiration from Facebook, and this a normal place for a post button.
