### ISSUE TITLE
Forgot password doesn't do anything

### ISSUE THREAD

**Issue by JPSharp** [SCCapstone/CampusConnect#174]
After clicking on forgot password a popup says that a link will be emailed to you. I have waited several hours and nothing has gone to my email.

**Comment by econnerty** [comment]
Feature is not implemented. Sorry for the confusion. Firebase does not play nicely with the schools filters, and we are not sure if we will even be able to enable this right now.

**Comment by econnerty** [comment]
What do you recommend @josemvidal ? The school will delete anything from firebase unless you go to microsoft quarantine and manually prevent it. It will even automatically click the link, typically invalidating it before the user can even get there. We still do not want to allow non usc emails to sign up though.
