### ISSUE TITLE
Clubs do not have pages?

### ISSUE THREAD

**Issue by JPSharp** [SCCapstone/CampusConnect#175]
When you click on the clubs a popup appears saying this is where the club page would be.

In the future you should make a demo page that has some other information, not just a popup.

**Comment by econnerty** [comment]
@challison404 This is your task for the rest of the year.

**Comment by econnerty** [comment]
We are working on a scraper to get all 600 clubs into our database, which will display on this page and then linkup with the relevant website when they are pressed on.
