### ISSUE TITLE
Event Detail page should show date

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/CampusConnect#201]
<img width="388" alt="image" src="https://user-images.githubusercontent.com/228704/229774776-550b2ced-8d71-4e9a-beba-722c56ac107e.png">

**Comment by NSarmadi** [comment]
![image](https://user-images.githubusercontent.com/70228634/230241224-be77a47b-4030-46fe-97cc-ea30ea008dba.png)
Closed w/ b43ec06, 730b22b, 0d2d6f1
