### ISSUE TITLE
Clubs should have a "more info"

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/CampusConnect#202]
If user wants to join a club, what do they do? 

The app should have a link/email/phone or some way the user can start learning how to join.

<img width="388" alt="image" src="https://user-images.githubusercontent.com/228704/229775518-7fca11d4-c86e-4ec8-98c7-077fe591810e.png">

**Comment by challison404** [comment]
Addressed this through the creation of an updated club scraper. It will now get the links associated with each club from the website "https://garnetgate.sa.sc.edu/organizations". If the user clicks on a club it will bring them to this link, assuming there was one available and it was scraped without error
