### ISSUE TITLE
Profile photo is not updated on chat

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/CampusConnect#205]
If the other person updated their Profile photo, it does not get updated in the chat. Even for new messages.

I also tried re-starting the app (later) but that did not fix it either.

https://user-images.githubusercontent.com/228704/229790149-96b4ccd1-a7ae-430f-9b7a-738e5424800a.mp4

**Comment by econnerty** [comment]
In theory, it would work on sign out, but this is a known issue.

**Comment by econnerty** [comment]
You have to sign out and sign back in. It's not ideal, but I'm not going to risk changing the way the chats work this late in the semester. Labeling this a won't fix.

**Comment by econnerty** [comment]
https://github.com/GetStream/stream-chat-js/issues/217

nvm, will fix
