### ISSUE TITLE
Header on the Home and Alumni Page is cut off by Sort Button

### ISSUE THREAD

**Issue by TylerTBarrett** [SCCapstone/CampusConnect#210]
See Title. Left screenshots below. If you need it to determine my screen size, I'm using a galaxy S8 edge.

<img src="https://user-images.githubusercontent.com/77293077/230737894-dbbeb574-af8e-4588-8655-b1b550f84bec.jpg" width="200" height="350">

<img src="https://user-images.githubusercontent.com/77293077/230737939-f70a6a11-6b9e-4b8e-a15f-b4706cbb5b06.jpg" width="200" height="350">

**Comment by econnerty** [comment]
There must be some prop to dynamically size this text.
