### ISSUE TITLE
Select Start time and Start time

### ISSUE THREAD

**Issue by TylerTBarrett** [SCCapstone/CampusConnect#211]
On the Calendar page when you're adding a new class, the selectors have you select the Start time and Start time instead of the Start and End Time. Screenshots below

<img src="https://user-images.githubusercontent.com/77293077/230738257-d49581f5-20f2-453f-bb63-d8a856cbd1ea.jpg" height="500" width="300">

**Comment by NSarmadi** [comment]
![image](https://user-images.githubusercontent.com/70228634/230781783-39222958-81f8-4e13-a672-0133419ee3aa.png)
