### ISSUE TITLE
Profile picture does not update after picking one on registration info page

### ISSUE THREAD

**Issue by nathandolbir** [SCCapstone/CampusConnect#225]
After filling in email and password, the info page shows up, but I am unable to see my uploaded picture other than the "pic uploaded" text
 showing
https://user-images.githubusercontent.com/75330713/230807377-173b4679-f4e6-4de3-94c4-9957ceb1bec5.mp4

**Comment by NSarmadi** [comment]
Can you re-upload this picture? @nathandolbir

**Comment by nathandolbir** [comment]
https://user-images.githubusercontent.com/75330713/230813836-b8f682cd-19da-4ab2-a54f-5bfc09807825.mp4

**Comment by nathandolbir** [comment]
Maybe related to @econnerty comment at https://github.com/SCCapstone/CampusConnect/issues/230#issuecomment-1501308242 ?

Sorry to make things unnecessarily tough on y'all lol

**Comment by econnerty** [comment]
It's not supposed to update there or on the edit profile screen (it's not implemented yet), but it should have left you click update or register, and the picture should have showed up. I think there is a bug related to the way your name was setup that won't let you change it on the edit profile screen, or there is something else going on that we are not sure of yet.

**Comment by econnerty** [comment]
Reopening and labeling this as an enhancement, because we would like the picture to display there immediately so the user can see what their profile pic will look like.
