### ISSUE TITLE
Editing profile does not allow me to finish

### ISSUE THREAD

**Issue by nathandolbir** [SCCapstone/CampusConnect#230]
Attempted to edit my profile picture and then submit, but I get an error and cannot submit my edits.

https://user-images.githubusercontent.com/75330713/230810879-6457a790-b59f-4fcb-9c0b-f039da40d846.mp4

**Comment by econnerty** [comment]
This one is probably ultimately a product of letting you sign up as "Nathan 243) Dolbir" which needs to be patched
