### ISSUE TITLE
Cannot swipe back a post when swiping right for replies

### ISSUE THREAD

**Issue by kfairey11** [SCCapstone/CampusConnect#234]
When I swiped right to view replies, the post is still swiped to the right a bit when I exited out of the replies. When I try to swipe it back into place, it just takes me to the replies again and the post is forever off-centered.

**Comment by econnerty** [comment]
A picture or video would help figure this one out

**Comment by kfairey11** [comment]
https://user-images.githubusercontent.com/77368958/230977042-426d60f8-3610-4b0b-ae6b-7842d7a100b8.MP4

**Comment by econnerty** [comment]
ios bugs wont be fixed
