### ISSUE TITLE
App Crashes when tapping recently sent message in groups and other places.

### ISSUE THREAD

**Issue by cwmiles** [SCCapstone/CampusConnect#237]
See videos below, this occurs in groups and p2p direct messages.

https://user-images.githubusercontent.com/70288320/231037907-b481a64f-c713-4adf-bcb2-0257f58c8d36.MOV

https://user-images.githubusercontent.com/70288320/231037968-746f58a8-7df8-4945-882d-6b7ce615634f.MOV

**Comment by econnerty** [comment]
weird

**Comment by cwmiles** [comment]
This is on flight, and i'm testing on ios, iPhone 12 pro. @econnerty

**Comment by NSarmadi** [comment]
what iOS version @cwmiles ?

**Comment by cwmiles** [comment]
im on 16.3.1

**Comment by econnerty** [comment]
okay, could be a new iOS thing. we are all onb old versions it seems

**Comment by cwmiles** [comment]
https://user-images.githubusercontent.com/70288320/231042477-1d039d05-7995-4592-8c92-a00f5604729f.MOV

similar issue so adding this here,
the app is also crashing when clicking the camera icon, and also when clicking chat history part of  the screen after having the keyboard up.

**Comment by econnerty** [comment]
^ you should create a separate issue for this because afaik it is a different issue that we were aware of internally. I need to add some permissions to the plist that allow camera access, or apple security will kick in a and throw a fit

**Comment by econnerty** [comment]
possibly fixed, but wont fix if not.
