### ISSUE TITLE
Upvote not completely visible on a post with a picture

### ISSUE THREAD

**Issue by Bryson2809** [SCCapstone/CampusConnect#239]

**Comment by Bryson2809** [comment]
[
![upvote](https://user-images.githubusercontent.com/70281849/231041159-86bc4ba2-aabe-46d5-a53b-e268f98e7af8.jpg)

**Comment by econnerty** [comment]
can you take a video? Is it just stuck like that after swiping?

**Comment by Bryson2809** [comment]
https://user-images.githubusercontent.com/70281849/231043239-d5b1a424-ca8c-4616-9197-93eceb971528.mp4

**Comment by Bryson2809** [comment]
It just gets stuck there

**Comment by econnerty** [comment]
Another instance where dynamically altering component size at runtime based off of the screens width would solve a problem.
