### ISSUE TITLE
Post with photo goes off the left side of the screen

### ISSUE THREAD

**Issue by Bryson2809** [SCCapstone/CampusConnect#240]
![photo](https://user-images.githubusercontent.com/70281849/231041246-39b09a66-f9d9-42fd-b87d-c927fcb7d6c1.jpg)

**Comment by econnerty** [comment]
Ultimately, the way to fix bugs like this is to dynamically render components using the screens dimensions.

You get the width of the screen at runtime, and the make everything a scalar based off of that value.
