### ISSUE TITLE
App Crashes when clicking Camera Icon/ touching the chat box in Messages

### ISSUE THREAD

**Issue by cwmiles** [SCCapstone/CampusConnect#241]
https://user-images.githubusercontent.com/70288320/231045165-ae418eac-641b-423c-a6f3-279f9134b1a2.MOV

Note: this error where the screen moves up and the app is caused to crash happens when the keyboard is closed after tapping the gif icon as well.

**Comment by econnerty** [comment]
Will fix this by adding camera permissions to the plist
