### ISSUE TITLE
UI changes on upvote messages on ios

### ISSUE THREAD

**Issue by cwmiles** [SCCapstone/CampusConnect#244]
![image](https://user-images.githubusercontent.com/70288320/231168137-d9456284-66c9-47d6-ac65-c6368c9d89cd.jpeg)

The colors are different here in messages when upvoting or downvoting, in comparison to the home feed.

**Comment by econnerty** [comment]
Technically not a bug. The way it is on the home feed may need to be changed for a multitude of reasons to match this one though.

We will probably not be doing this for 1.0 release though.

**Comment by econnerty** [comment]
not a bug
