### ISSUE TITLE
Only Clubs at the beginning of the alphabet are displayed

### ISSUE THREAD

**Issue by TylerTBarrett** [SCCapstone/CampusConnect#245]
Looks like only the clubs at the start of the alphabet are displayed. It cuts off at B and doesn't load any more when scrolling down. 

https://user-images.githubusercontent.com/77293077/231617353-60f7d1d7-7f42-4454-9ba3-6fa5d94249c9.mp4

**Comment by challison404** [comment]
Duplicate #141
